# -*- encoding: utf-8 -*-
##############################################################################
#
#    Copyright (c) 2012 Allianz Technology, A subsidiary of SAT Group, Inc.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
{
    'name': 'Add-on for account_financial_report Module',
    'version': '3.0',
    'category': 'Generic Modules/Reporting',
    'description': """ This module ensures that the Balance Sheets generated by the account_financial_report module balance out.""",
    'author': 'Allianz Technology',
    'website': 'www.allianztechnology.com',
    'depends': [
        'account_financial_report',
    ],
    'init_xml': [],
    'update_xml': [
        'wizard/financial_report_wizard_view.xml',
        'report/financial_report_view.xml'
    ],
    'demo_xml': [],
    'test': [],
    'installable': True,
    'active': False,
    'certificate': '',
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
